package com.knowlink.api.tutors.availability.data.mappers;

import com.knowlink.api.tutors.availability.controllers.requests.AvailabilityBlockRequest;
import com.knowlink.api.tutors.availability.controllers.responses.AvailabilityBlockResponse;
import com.knowlink.api.tutors.availability.data.models.AvailabilityBlock;
import com.knowlink.api.tutors.data.models.TutorProfile;
import org.springframework.stereotype.Component;

@Component
public class AvailabilityBlockMapper {

    public AvailabilityBlock toEntity(AvailabilityBlockRequest request, TutorProfile tutorProfile) {
        return AvailabilityBlock.builder()
                .date(request.date())
                .startTime(request.startTime())
                .endTime(request.endTime())
                .repeatWeekly(request.repeatWeekly())
                .autoGenerated(false)
                .available(true)
                .tutorProfile(tutorProfile)
                .build();
    }

    public AvailabilityBlock toGeneratedCopy(AvailabilityBlock origin, java.time.LocalDate date) {
        return AvailabilityBlock.builder()
                .date(date)
                .startTime(origin.getStartTime())
                .endTime(origin.getEndTime())
                .repeatWeekly(true)
                .autoGenerated(true)
                .available(true)
                .tutorProfile(origin.getTutorProfile())
                .build();
    }

    public AvailabilityBlockResponse toResponse(AvailabilityBlock block) {
        return new AvailabilityBlockResponse(
                block.getAvailabilityBlockId(),
                block.getDate(),
                block.getStartTime(),
                block.getEndTime(),
                block.isRepeatWeekly(),
                block.isAutoGenerated());
    }
}