package com.knowlink.api.tutors.availability.controllers.responses;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.UUID;

public record AvailabilityBlockResponse(
        UUID availabilityBlockId,
        LocalDate date,
        LocalTime startTime,
        LocalTime endTime,
        boolean repeatWeekly,
        boolean autoGenerated
) {}