jwt:
  secret: ${JWT_SECRET:ZmFrZV9zZWNyZXRfZm9yX2Rldg==} # base64 fake_secret_for_dev, set JWT_SECRET env var in prod
  access-token-expiration: ${JWT_EXPIRATION:3600000}

frontend:
  url: ${FRONTEND_URL}

app:
  url: ${APP_URL}
  default-profile-picture: ${DEFAULT_PROFILE_PICTURE_URL}

spring:
  cache:
    type: none

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

notifications:
  use-email: false
