package com.knowlink.api.tutors.availability.data.models;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.knowlink.api.tutors.data.models.TimeSlot;
import com.knowlink.api.tutors.data.models.TutorProfile;

@Entity
@Table(name = "availability_block")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AvailabilityBlock {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "availability_block_id", updatable = false, nullable = false)
    private UUID availabilityBlockId;

    @Column(name = "date", nullable = false)
    private LocalDate date;

    @Column(name = "start_time", nullable = false)
    private LocalTime startTime;

    @Column(name = "end_time", nullable = false)
    private LocalTime endTime;

    @Column(name = "available", nullable = false)
    @Builder.Default
    private boolean available = true;

    @Column(name = "repeat_weekly", nullable = false)
    @Builder.Default
    private boolean repeatWeekly = false;

    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private boolean autoGenerated = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tutor_profile_id", nullable = false)
    private TutorProfile tutorProfile;

    @OneToMany(mappedBy = "availabilityBlock", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<TimeSlot> generatedSlots = new ArrayList<>();
}