package com.knowlink.api.tutors.availability.services.implementations;

import com.knowlink.api.tutors.availability.controllers.requests.AvailabilityBlockRequest;
import com.knowlink.api.tutors.availability.controllers.responses.AvailabilityBlockResponse;
import com.knowlink.api.tutors.availability.data.mappers.AvailabilityBlockMapper;
import com.knowlink.api.tutors.availability.data.models.AvailabilityBlock;
import com.knowlink.api.tutors.availability.repositories.IAvailabilityBlockRepository;
import com.knowlink.api.tutors.availability.services.interfaces.IAvailabilityBlockService;
import com.knowlink.api.tutors.availability.utils.AvailabilityConstants;
import com.knowlink.api.tutors.availability.validations.IAvailabilityBlockValidationService;
import com.knowlink.api.tutors.data.models.TutorProfile;
import com.knowlink.api.tutors.validations.ITutorProfileValidationService;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class AvailabilityBlockServiceImpl implements IAvailabilityBlockService {

    private final IAvailabilityBlockRepository availabilityBlockRepository;
    private final ITutorProfileValidationService tutorProfileValidationService;
    private final IAvailabilityBlockValidationService availabilityBlockValidationService;
    private final AvailabilityBlockMapper availabilityBlockMapper;

    @Override
    @Transactional
    public List<AvailabilityBlockResponse> replaceWeekBlocks(
            UUID tutorUserId,
            LocalDate weekStart,
            LocalDate weekEnd,
            List<AvailabilityBlockRequest> blocks) {

        availabilityBlockValidationService.validateBlocks(blocks);

        TutorProfile tutorProfile = tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId);
        UUID tutorProfileId = tutorProfile.getTutorProfileId();

        boolean anyRepeat = blocks.stream().anyMatch(request -> Boolean.TRUE.equals(request.repeatWeekly()));

        if (anyRepeat) {
            LocalDate repeatWindowEnd = weekEnd.plusWeeks(AvailabilityConstants.REPEAT_WEEKS_AHEAD);
            availabilityBlockRepository.deleteInRange(tutorProfileId, weekStart, repeatWindowEnd);
        } else {
            availabilityBlockRepository.deleteInRange(tutorProfileId, weekStart, weekEnd);
            availabilityBlockRepository.deleteAutoGeneratedFrom(tutorProfileId, weekStart);
        }

        List<AvailabilityBlock> toSave = new ArrayList<>();

        for (AvailabilityBlockRequest request : blocks) {
            AvailabilityBlock origin = availabilityBlockMapper.toEntity(request, tutorProfile);
            toSave.add(origin);

            if (Boolean.TRUE.equals(request.repeatWeekly())) {
                for (int i = 1; i <= AvailabilityConstants.REPEAT_WEEKS_AHEAD; i++) {
                    LocalDate futureDate = request.date().plusWeeks(i);
                    toSave.add(availabilityBlockMapper.toGeneratedCopy(origin, futureDate));
                }
            }
        }

        availabilityBlockRepository.saveAll(toSave);

        return availabilityBlockRepository.findInRange(tutorProfileId, weekStart, weekEnd)
                .stream()
                .map(availabilityBlockMapper::toResponse)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public List<AvailabilityBlockResponse> getBlocksInRange(UUID tutorUserId, LocalDate from, LocalDate to) {
        TutorProfile tutorProfile = tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId);

        return availabilityBlockRepository.findInRange(tutorProfile.getTutorProfileId(), from, to)
                .stream()
                .map(availabilityBlockMapper::toResponse)
                .toList();
    }
}