package com.knowlink.api.tutors.schedule.services;

import com.knowlink.api.bookings.controllers.responses.BookingResponse;
import com.knowlink.api.bookings.data.enums.BookingStatus;
import com.knowlink.api.bookings.data.mappers.BookingMapper;
import com.knowlink.api.bookings.data.models.Booking;
import com.knowlink.api.bookings.repositories.IBookingRepository;
import com.knowlink.api.tutors.availability.controllers.responses.AvailabilityBlockResponse;
import com.knowlink.api.tutors.availability.data.enums.BookingStatusGroups;
import com.knowlink.api.tutors.availability.data.models.AvailabilityBlock;
import com.knowlink.api.tutors.availability.repositories.IAvailabilityBlockRepository;
import com.knowlink.api.tutors.availability.services.interfaces.IAvailabilityBlockService;
import com.knowlink.api.tutors.data.models.Career;
import com.knowlink.api.tutors.data.models.TutorProfile;
import com.knowlink.api.tutors.data.models.TutorSubject;
import com.knowlink.api.tutors.schedule.controllers.responses.WeeklyScheduleResponse;
import com.knowlink.api.tutors.schedule.services.implementations.TutorWeeklyScheduleServiceImpl;
import com.knowlink.api.tutors.validations.ITutorProfileValidationService;
import com.knowlink.api.users.data.models.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class TutorWeeklyScheduleServiceImplTest {

    @Mock
    private ITutorProfileValidationService tutorProfileValidationService;
    @Mock
    private IAvailabilityBlockService availabilityBlockService;
    @Mock
    private IAvailabilityBlockRepository availabilityBlockRepository;
    @Mock
    private IBookingRepository bookingRepository;
    @Mock
    private BookingMapper bookingMapper;

    private TutorWeeklyScheduleServiceImpl service;

    private final UUID tutorUserId = UUID.randomUUID();
    private final UUID tutorProfileId = UUID.randomUUID();
    private final LocalDate monday = LocalDate.now().plusWeeks(1).with(java.time.DayOfWeek.MONDAY);
    private final LocalDate sunday = monday.plusDays(6);

    @BeforeEach
    void setUp() {
        service = new TutorWeeklyScheduleServiceImpl(
                tutorProfileValidationService,
                availabilityBlockService,
                availabilityBlockRepository,
                bookingRepository,
                bookingMapper);
    }

    private TutorProfile buildTutorProfile() {
        User user = User.builder().userId(tutorUserId).fullName("Ana García").build();
        Career career = Career.builder().name("Ingeniería en Sistemas").build();
        return TutorProfile.builder()
                .tutorProfileId(tutorProfileId)
                .user(user)
                .career(career)
                .build();
    }

    private AvailabilityBlock buildAvailabilityBlock(LocalDate date, LocalTime start, LocalTime end, boolean available) {
        TutorProfile profile = buildTutorProfile();
        return AvailabilityBlock.builder()
                .availabilityBlockId(UUID.randomUUID())
                .date(date)
                .startTime(start)
                .endTime(end)
                .available(available)
                .repeatWeekly(false)
                .autoGenerated(false)
                .tutorProfile(profile)
                .build();
    }

    private Booking buildBooking(LocalDate date, LocalTime start, LocalTime end, BookingStatus status) {
        User student = User.builder().userId(UUID.randomUUID()).fullName("Carlos López").build();
        User tutor = User.builder().userId(tutorUserId).fullName("Ana García").build();
        TutorProfile profile = buildTutorProfile();
        TutorSubject tutorSubject = TutorSubject.builder()
                .tutorSubjectId(UUID.randomUUID())
                .tutorProfile(profile)
                .subject(null)
                .build();
        return Booking.builder()
                .bookingId(UUID.randomUUID())
                .sessionDate(date)
                .startTime(start)
                .endTime(end)
                .amount(BigDecimal.valueOf(1500))
                .bookingStatus(status)
                .tutorSubject(tutorSubject)
                .student(student)
                .tutor(tutor)
                .build();
    }

    @Test
    @DisplayName("CP-052.01 - Semana con actividad devuelve summary correcto")
    void getWeeklySchedule_withActivity_returnsCorrectSummary() {
        when(tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId))
                .thenReturn(buildTutorProfile());

        AvailabilityBlockResponse blockResponse = new AvailabilityBlockResponse(
                UUID.randomUUID(), monday, LocalTime.of(9, 0), LocalTime.of(10, 0), false, false);
        when(availabilityBlockService.getBlocksInRange(tutorUserId, monday, sunday))
                .thenReturn(List.of(blockResponse));

        Booking booking1 = buildBooking(monday, LocalTime.of(10, 0), LocalTime.of(11, 0), BookingStatus.BOOKED);
        Booking booking2 = buildBooking(monday, LocalTime.of(14, 0), LocalTime.of(15, 0), BookingStatus.BOOKED);
        Booking booking3 = buildBooking(monday.plusDays(2), LocalTime.of(9, 0), LocalTime.of(10, 0), BookingStatus.PENDING);
        when(bookingRepository.findActiveBookingsInRange(tutorUserId, monday, sunday, BookingStatusGroups.ACTIVE))
                .thenReturn(List.of(booking1, booking2, booking3));

        BookingResponse response1 = new BookingResponse(
                booking1.getBookingId(), monday, LocalTime.of(10, 0), LocalTime.of(11, 0),
                BigDecimal.valueOf(1500), null, null, BookingStatus.BOOKED, null, null, null);
        BookingResponse response2 = new BookingResponse(
                booking2.getBookingId(), monday, LocalTime.of(14, 0), LocalTime.of(15, 0),
                BigDecimal.valueOf(1500), null, null, BookingStatus.BOOKED, null, null, null);
        BookingResponse response3 = new BookingResponse(
                booking3.getBookingId(), monday.plusDays(2), LocalTime.of(9, 0), LocalTime.of(10, 0),
                BigDecimal.valueOf(1500), null, null, BookingStatus.PENDING, null, null, null);
        when(bookingMapper.toResponse(booking1)).thenReturn(response1);
        when(bookingMapper.toResponse(booking2)).thenReturn(response2);
        when(bookingMapper.toResponse(booking3)).thenReturn(response3);

        AvailabilityBlock freeBlock1 = buildAvailabilityBlock(monday, LocalTime.of(9, 0), LocalTime.of(10, 0), true);
        AvailabilityBlock freeBlock2 = buildAvailabilityBlock(monday, LocalTime.of(11, 0), LocalTime.of(12, 0), true);
        AvailabilityBlock busyBlock = buildAvailabilityBlock(monday, LocalTime.of(10, 0), LocalTime.of(11, 0), false);
        when(availabilityBlockRepository.findInRange(eq(tutorProfileId), eq(monday), eq(sunday), any(), any()))
                .thenReturn(List.of(freeBlock1, freeBlock2, busyBlock));

        WeeklyScheduleResponse result = service.getWeeklySchedule(tutorUserId, monday, sunday);

        assertThat(result.from()).isEqualTo(monday);
        assertThat(result.to()).isEqualTo(sunday);
        assertThat(result.availabilityBlocks()).hasSize(1);
        assertThat(result.bookings()).hasSize(3);
        assertThat(result.summary().confirmedBookingsCount()).isEqualTo(2);
        assertThat(result.summary().freeBlocksCount()).isEqualTo(2);
        assertThat(result.summary().nextClass()).isNotNull();
        assertThat(result.summary().nextClass().bookingId()).isEqualTo(booking1.getBookingId());
    }

    @Test
    @DisplayName("CP-052.02 - Semana sin actividad devuelve listas vacias y summary en cero")
    void getWeeklySchedule_emptyWeek_returnsEmptyWithZeroSummary() {
        when(tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId))
                .thenReturn(buildTutorProfile());

        when(availabilityBlockService.getBlocksInRange(tutorUserId, monday, sunday))
                .thenReturn(List.of());

        when(bookingRepository.findActiveBookingsInRange(tutorUserId, monday, sunday, BookingStatusGroups.ACTIVE))
                .thenReturn(List.of());

        when(availabilityBlockRepository.findInRange(eq(tutorProfileId), eq(monday), eq(sunday), any(), any()))
                .thenReturn(List.of());

        WeeklyScheduleResponse result = service.getWeeklySchedule(tutorUserId, monday, sunday);

        assertThat(result.from()).isEqualTo(monday);
        assertThat(result.to()).isEqualTo(sunday);
        assertThat(result.availabilityBlocks()).isEmpty();
        assertThat(result.bookings()).isEmpty();
        assertThat(result.summary().confirmedBookingsCount()).isEqualTo(0);
        assertThat(result.summary().freeBlocksCount()).isEqualTo(0);
        assertThat(result.summary().nextClass()).isNull();
    }

    @Test
    @DisplayName("CP-052.03 - nextClass apunta a la reserva BOOKED mas proxima")
    void getWeeklySchedule_multipleBookings_nextClassIsNearestBooked() {
        when(tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId))
                .thenReturn(buildTutorProfile());

        when(availabilityBlockService.getBlocksInRange(tutorUserId, monday, sunday))
                .thenReturn(List.of());

        Booking fartherBooking = buildBooking(monday.plusDays(3), LocalTime.of(14, 0), LocalTime.of(15, 0), BookingStatus.BOOKED);
        Booking nearerBooking = buildBooking(monday, LocalTime.of(9, 0), LocalTime.of(10, 0), BookingStatus.BOOKED);
        Booking pastBooking = buildBooking(LocalDate.now().minusDays(3), LocalTime.of(10, 0), LocalTime.of(11, 0), BookingStatus.BOOKED);
        when(bookingRepository.findActiveBookingsInRange(tutorUserId, monday, sunday, BookingStatusGroups.ACTIVE))
                .thenReturn(List.of(fartherBooking, nearerBooking, pastBooking));

        when(bookingMapper.toResponse(any())).thenReturn(null);

        when(availabilityBlockRepository.findInRange(eq(tutorProfileId), eq(monday), eq(sunday), any(), any()))
                .thenReturn(List.of());

        WeeklyScheduleResponse result = service.getWeeklySchedule(tutorUserId, monday, sunday);

        assertThat(result.summary().nextClass()).isNotNull();
        assertThat(result.summary().nextClass().sessionDate()).isEqualTo(monday);
        assertThat(result.summary().nextClass().startTime()).isEqualTo(LocalTime.of(9, 0));
    }

    @Test
    @DisplayName("CP-052.04 - Semana pasada no filtra reservas")
    void getWeeklySchedule_pastWeek_returnsBookingsFromPast() {
        LocalDate pastMonday = LocalDate.now().minusWeeks(2).with(java.time.DayOfWeek.MONDAY);
        LocalDate pastSunday = pastMonday.plusDays(6);

        when(tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId))
                .thenReturn(buildTutorProfile());

        when(availabilityBlockService.getBlocksInRange(tutorUserId, pastMonday, pastSunday))
                .thenReturn(List.of());

        Booking pastBooking = buildBooking(pastMonday.plusDays(2), LocalTime.of(10, 0), LocalTime.of(11, 0), BookingStatus.BOOKED);
        when(bookingRepository.findActiveBookingsInRange(tutorUserId, pastMonday, pastSunday, BookingStatusGroups.ACTIVE))
                .thenReturn(List.of(pastBooking));

        BookingResponse pastResponse = new BookingResponse(
                pastBooking.getBookingId(), pastMonday.plusDays(2), LocalTime.of(10, 0), LocalTime.of(11, 0),
                BigDecimal.valueOf(1500), null, null, BookingStatus.BOOKED, null, null, null);
        when(bookingMapper.toResponse(pastBooking)).thenReturn(pastResponse);

        when(availabilityBlockRepository.findInRange(eq(tutorProfileId), eq(pastMonday), eq(pastSunday), any(), any()))
                .thenReturn(List.of());

        WeeklyScheduleResponse result = service.getWeeklySchedule(tutorUserId, pastMonday, pastSunday);

        assertThat(result.bookings()).hasSize(1);
        assertThat(result.bookings().get(0).sessionDate()).isEqualTo(pastMonday.plusDays(2));
    }

    @Test
    @DisplayName("CP-052.05 - No hay nextClass cuando no hay reservas BOOKED futuras")
    void getWeeklySchedule_noFutureBookings_nextClassIsNull() {
        when(tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId))
                .thenReturn(buildTutorProfile());

        when(availabilityBlockService.getBlocksInRange(tutorUserId, monday, sunday))
                .thenReturn(List.of());

        Booking pastBooking = buildBooking(LocalDate.now().minusDays(3), LocalTime.of(10, 0), LocalTime.of(11, 0), BookingStatus.BOOKED);
        when(bookingRepository.findActiveBookingsInRange(tutorUserId, monday, sunday, BookingStatusGroups.ACTIVE))
                .thenReturn(List.of(pastBooking));

        when(bookingMapper.toResponse(pastBooking)).thenReturn(null);

        when(availabilityBlockRepository.findInRange(eq(tutorProfileId), eq(monday), eq(sunday), any(), any()))
                .thenReturn(List.of());

        WeeklyScheduleResponse result = service.getWeeklySchedule(tutorUserId, monday, sunday);

        assertThat(result.summary().confirmedBookingsCount()).isEqualTo(1);
        assertThat(result.summary().nextClass()).isNull();
    }

    @Test
    @DisplayName("CP-052.06 - Solo reservas BOOKED cuentan como confirmadas, no PENDING ni IN_PROGRESS")
    void getWeeklySchedule_onlyBookedCountAsConfirmed() {
        when(tutorProfileValidationService.findTutorProfileOrThrowException(tutorUserId))
                .thenReturn(buildTutorProfile());

        when(availabilityBlockService.getBlocksInRange(tutorUserId, monday, sunday))
                .thenReturn(List.of());

        Booking booked = buildBooking(monday, LocalTime.of(10, 0), LocalTime.of(11, 0), BookingStatus.BOOKED);
        Booking pending = buildBooking(monday.plusDays(1), LocalTime.of(10, 0), LocalTime.of(11, 0), BookingStatus.PENDING);
        Booking inProgress = buildBooking(monday.plusDays(2), LocalTime.of(10, 0), LocalTime.of(11, 0), BookingStatus.IN_PROGRESS);
        when(bookingRepository.findActiveBookingsInRange(tutorUserId, monday, sunday, BookingStatusGroups.ACTIVE))
                .thenReturn(List.of(booked, pending, inProgress));

        when(bookingMapper.toResponse(any())).thenReturn(null);

        when(availabilityBlockRepository.findInRange(eq(tutorProfileId), eq(monday), eq(sunday), any(), any()))
                .thenReturn(List.of());

        WeeklyScheduleResponse result = service.getWeeklySchedule(tutorUserId, monday, sunday);

        assertThat(result.bookings()).hasSize(3);
        assertThat(result.summary().confirmedBookingsCount()).isEqualTo(1);
    }
}
