package com.knowlink.api.tutors.availability.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.knowlink.api.tutors.availability.data.models.AvailabilityBlock;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.UUID;

public interface IAvailabilityBlockRepository extends JpaRepository<AvailabilityBlock, UUID> {

        @Query("""
                        SELECT ab FROM AvailabilityBlock ab
                        WHERE ab.tutorProfile.tutorProfileId = :tutorProfileId
                        AND ab.date BETWEEN :from AND :to
                        AND (ab.date > :today OR (ab.date = :today AND ab.endTime > :nowTime))
                        ORDER BY ab.date, ab.startTime
                        """)
        List<AvailabilityBlock> findInRange(
                        @Param("tutorProfileId") UUID tutorProfileId,
                        @Param("from") LocalDate from,
                        @Param("to") LocalDate to,
                        @Param("today") LocalDate today,
                        @Param("nowTime") LocalTime nowTime);

        @Modifying(clearAutomatically = true)
        @Query("""
                        DELETE FROM AvailabilityBlock ab
                        WHERE ab.tutorProfile.tutorProfileId = :tutorProfileId
                        AND ab.date BETWEEN :from AND :to
                        """)
        void deleteInRange(
                        @Param("tutorProfileId") UUID tutorProfileId,
                        @Param("from") LocalDate from,
                        @Param("to") LocalDate to);

        @Modifying(clearAutomatically = true)
        @Query("""
                        DELETE FROM AvailabilityBlock ab
                        WHERE ab.tutorProfile.tutorProfileId = :tutorProfileId
                        AND ab.autoGenerated = true
                        AND ab.date >= :from
                        """)
        void deleteAutoGeneratedFrom(
                        @Param("tutorProfileId") UUID tutorProfileId,
                        @Param("from") LocalDate from);

        @Query("""
                        SELECT ab FROM AvailabilityBlock ab
                        WHERE ab.tutorProfile.tutorProfileId = :tutorProfileId
                        AND ab.available = true
                        """)
        List<AvailabilityBlock> findAvailableByTutorProfileId(
                        @Param("tutorProfileId") UUID tutorProfileId);

        @Modifying(clearAutomatically = true)
        @Query("""
                        DELETE FROM AvailabilityBlock ab
                        WHERE (ab.date < :today OR (ab.date = :today AND ab.endTime <= :nowTime))
                        AND NOT EXISTS (SELECT 1 FROM TimeSlot ts WHERE ts.assignedBlock = ab)
                        """)
        void deletePastOrphaned(@Param("today") LocalDate today, @Param("nowTime") LocalTime nowTime);
}